__import__('pysqlite3')
import sys
sys.modules['sqlite3'] = sys.modules.pop('pysqlite3')

# From public libraries
import streamlit as st
import os
import shutil

from langchain_community.vectorstores import Chroma
from langchain_openai import OpenAIEmbeddings

from langchain.chains.retrieval import create_retrieval_chain
from langchain.chains.combine_documents import create_stuff_documents_chain
# from langchain.chains import RetrievalQA
from langchain.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI

from helper_functions import llm 
# from logics import user_query_handler2 

st.title('Find out about government programs offered by the Singapore Government here.')

form = st.form(key="form")
form.subheader("Prompt")

user_prompt = form.text_area("Enter your prompt here", height=150)

# urls = ["https://taxsummaries.pwc.com/singapore/corporate/tax-credits-and-incentives", "https://www.aseanbriefing.com/doing-business-guide/singapore/why-singapore/incentives-for-doing-business-in-singapore"]

# llm = ChatOpenAI(model='gpt-4o-mini')
# embeddings = OpenAIEmbeddings(model='text-embedding-3-small')

# compiled_text = user_query_handler2.content_compiler(urls)
# split_text = user_query_handler2.splitter(compiled_text)

# vector_store = Chroma.from_documents(
#     collection_name = "Gov_Support",
#     documents = split_text,
#     embedding = embeddings,
#     persist_directory = "./chroma_db"
# )

# if form.form_submit_button("Submit"):
#     # Get user input
#     st.toast(f"User Input Submitted - {user_prompt}")

#     prompt = ChatPromptTemplate.from_template("""
#     Use the following context to answer the user's question.

#     Context:
#     {context}

#     Question:
#     {input}
#     """)

#     chain = create_retrieval_chain(
#         retriever=vector_store.as_retriever(k=5),
#         combine_docs_chain=create_stuff_documents_chain(llm, prompt)
#     )

#     response = chain.invoke({"input": user_prompt})

#     # Display response generated by the LLM onto the frontend 
#     st.write(response["answer"])
#     print(response)

#     vector_store.delete_collection()


if form.form_submit_button("Submit"):
    # Get user input
    st.toast(f"User Input Submitted - {user_prompt}")

    prompt_1 = f"""
    You are a Singapore government official working for an investment promotion agency. An executive from a company asks you the questions within the delimiters.

    The company is a foreign company, and the executive is unfamiliar with Singapore.
    The executive would like to be motivated with reasons to come to Singapore, whether that be business opportunities, partnerships, or government programs in Singapore.
    
    Respond with relevant information on Singapore's offerings that could support the company to set up business activities or find partnerships in Singapore.
    The information should be specific with examples of programs, instead of providing broad strokes on Singapore's attractiveness for businesses.

    Think step by step.

    <company_query>
    {user_prompt}
    </company_query>

    """

    response_1 = llm.get_completion(prompt_1)

    prompt_2 = f"""
    Of the items suggested, elaborate on how they could be relevant for the company when setting up a business in Singapore. 
    
    Think step by step. Provide your response in 3 bullet points for each program.

    <items>
    {response_1}
    <items>

    """

    response_2 = llm.getcompletion(prompt_2)

    st.write(response_2["answer"])
    print(response_2)